kind: pipeline
name: build
image_pull_secrets:
  - docker_pull_secrets
steps:
  - name: build
    image: plugins/docker
    when:
      branch:
        - master
    environment:
      NODE_ENV: production
      SERVER_URL: ws://apps.caseywebb.xyz/growhaus/api
      WEB_UI_URL: https://apps.caseywebb.xyz/growhaus
    settings:
      repo: containers.caseywebb.xyz/growhaus/builder
      target: builder
      cache_from: containers.caseywebb.xyz/growhaus/builder
      registry: containers.caseywebb.xyz
      custom_dns: 10.0.0.136
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass

---
kind: pipeline
name: lib
depends_on:
  - build
image_pull_secrets:
  - docker_pull_secrets
steps:
  - name: publish:lib
    image: containers.caseywebb.xyz/growhaus/builder
    when:
      branch:
        - master
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - mv ./.git /repo/lib
      - cd /repo/lib
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" >> .npmrc
      - npx fluid-publish changesCmd=true devTag=$DRONE_COMMIT

---
kind: pipeline
name: agent
depends_on:
  - build
  - lib
image_pull_secrets:
  - docker_pull_secrets
steps:
  - name: publish:agent
    image: containers.caseywebb.xyz/growhaus/builder
    when:
      branch:
        - master
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - mv ./.git /repo/agent
      - cd /repo/agent
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" >> .npmrc
      - yarn add @caseywebb/growhaus@$DRONE_COMMIT
      - npx fluid-publish changesCmd=true devTag=latest
  - name: deploy:agent
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      port: 22
      script:
        - update_growhaus_agent
    depends_on:
      - publish:agent
---
kind: pipeline
name: server
depends_on:
  - build
image_pull_secrets:
  - docker_pull_secrets
steps:
  - name: publish:server
    image: plugins/docker
    when:
      branch:
        - master
    environment:
      DARK_SKY_API_KEY:
        from_secret: dark_sky_api_key
    settings:
      repo: containers.caseywebb.xyz/growhaus/server
      target: server
      cache_from: containers.caseywebb.xyz/growhaus/builder
      registry: containers.caseywebb.xyz
      custom_dns: 10.0.0.136
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
  - name: deploy:server
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      port: 22
      script:
        - update_growhaus_server
    depends_on:
      - publish:server

---
kind: pipeline
name: web
depends_on:
  - build
image_pull_secrets:
  - docker_pull_secrets
steps:
  - name: publish:web
    image: plugins/docker
    when:
      branch:
        - master
    settings:
      repo: containers.caseywebb.xyz/growhaus/web
      target: web
      cache_from: containers.caseywebb.xyz/growhaus/builder
      registry: containers.caseywebb.xyz
      custom_dns: 10.0.0.136
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
  - name: deploy:web
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      port: 22
      script:
        - update_growhaus_web
    depends_on:
      - publish:web
