kind: pipeline
name: build
steps:
  - name: cache:restore
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: build
    image: node:lts-alpine
    when:
      branch:
        - master
    environment:
      NODE_ENV: production
      NPM_TOKEN:
        from_secret: npm_token
      SERVER_URL: wss://apps.caseywebb.xyz/growhaus/api
      WEB_UI_URL: https://apps.caseywebb.xyz/growhaus
    commands:
      - apk add git python2
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" >> .npmrc
      - yarn install --pure-lockfile --ignore-optional
      - ls
      - pwd
      - yarn build
      - yarn lerna publish major --yes --canary --dist-tag canary
  - name: cache:rebuild
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
volumes:
  - name: cache
    host:
      path: /var/cache/growhaus
---
kind: pipeline
name: agent
clone:
  disable: true
depends_on:
  - build
steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      port: 22
      script:
        - update_growhaus_agent
      command_timeout: 3m

---
kind: pipeline
name: server
clone:
  disable: true
depends_on:
  - build
steps:
  - name: image
    image: plugins/docker:18.09
    when:
      branch:
        - master
    settings:
      dockerfile: server/Dockerfile
      repo: containers.caseywebb.xyz/growhaus/server
      target: server
      registry: containers.caseywebb.xyz
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      purge: true
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      port: 22
      script:
        - update_growhaus_server

---
kind: pipeline
name: web
clone:
  disable: true
depends_on:
  - build
steps:
  - name: image
    image: plugins/docker:18.09
    when:
      branch:
        - master
    settings:
      dockerfile: web/Dockerfile
      repo: containers.caseywebb.xyz/growhaus/web
      target: web
      registry: containers.caseywebb.xyz
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      purge: true
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      port: 22
      script:
        - update_growhaus_web
