kind: pipeline
name: build
steps:
  - name: cache:restore
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./agent/node_modules
        - ./lib/node_modules
        - ./server/node_modules
        - ./web/node_modules
  - name: build
    image: node:lts
    environment:
      NODE_ENV: production
      NPM_TOKEN:
        from_secret: npm_token
      SERVER_URL: wss://apps.caseywebb.xyz/growhaus/api
      WEB_UI_URL: https://apps.caseywebb.xyz/growhaus
    commands:
      - yarn install --pure-lockfile --ignore-optional --production false
      - yarn build
  - name: publish
    image: node:lts
    when:
      branch:
        - master
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - git fetch --tags
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" >> .npmrc
      - yarn lerna publish major --yes --force-publish --canary --dist-tag canary
  - name: cache:rebuild
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./agent/node_modules
        - ./lib/node_modules
        - ./server/node_modules
        - ./web/node_modules
volumes:
  - name: cache
    host:
      path: /var/cache
---
kind: pipeline
name: deploy:agent
clone:
  disable: true
trigger:
  branch:
    - master
depends_on:
  - build
steps:
  - name: update
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      script:
        - update_growhaus_agent
      command_timeout: 3m

---
kind: pipeline
name: deploy:server
trigger:
  branch:
    - master
depends_on:
  - build
steps:
  - name: image
    image: plugins/docker:18.09
    settings:
      dockerfile: server/Dockerfile
      repo: containers.caseywebb.xyz/growhaus/server
      target: server
      registry: containers.caseywebb.xyz
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      purge: true
  - name: update
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      script:
        - update_growhaus_server

---
kind: pipeline
name: deploy:web
trigger:
  branch:
    - master
depends_on:
  - build
steps:
  - name: image
    image: plugins/docker:18.09
    settings:
      dockerfile: web/Dockerfile
      repo: containers.caseywebb.xyz/growhaus/web
      target: web
      registry: containers.caseywebb.xyz
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      purge: true
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      script:
        - update_growhaus_web
