kind: pipeline
name: build
image_pull_secrets:
  - docker_pull_secrets
steps:
  - name: build
    image: plugins/docker:18.09
    when:
      branch:
        - master
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    settings:
      repo: containers.caseywebb.xyz/growhaus/builder
      cache_from: containers.caseywebb.xyz/growhaus/builder
      registry: containers.caseywebb.xyz
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    commands:
      - mv .git /repo
      - cd /repo
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" >> .npmrc
      - npx lerna publish major --yes --canary --dist-tag canary

---
kind: pipeline
name: agent
clone:
  disable: true
depends_on:
  - build
steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      port: 22
      script:
        - update_growhaus_agent
      command_timeout: 3m

---
kind: pipeline
name: server
clone:
  disable: true
depends_on:
  - build
steps:
  - name: image
    image: plugins/docker:18.09
    when:
      branch:
        - master
    settings:
      dockerfile: server/Dockerfile
      repo: containers.caseywebb.xyz/growhaus/server
      target: server
      registry: containers.caseywebb.xyz
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      port: 22
      script:
        - update_growhaus_server

---
kind: pipeline
name: web
clone:
  disable: true
depends_on:
  - build
steps:
  - name: image
    image: plugins/docker:18.09
    when:
      branch:
        - master
    settings:
      dockerfile: web/Dockerfile
      repo: containers.caseywebb.xyz/growhaus/web
      target: web
      registry: containers.caseywebb.xyz
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: ssh.caseywebb.xyz
      username: growhaus
      key:
        from_secret: ssh_key
      port: 22
      script:
        - update_growhaus_web
